
package br.ufjf.pgcc.plscience.consumeservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConvertTemperature", targetNamespace = "http://webservice.plscience.pgcc.ufjf.br/", wsdlLocation = "http://localhost:8084/plscience-ecos/ConvertTemperature?wsdl")
public class ConvertTemperature_Service
    extends Service
{

    private final static URL CONVERTTEMPERATURE_WSDL_LOCATION;
    private final static WebServiceException CONVERTTEMPERATURE_EXCEPTION;
    private final static QName CONVERTTEMPERATURE_QNAME = new QName("http://webservice.plscience.pgcc.ufjf.br/", "ConvertTemperature");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8084/plscience-ecos/ConvertTemperature?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONVERTTEMPERATURE_WSDL_LOCATION = url;
        CONVERTTEMPERATURE_EXCEPTION = e;
    }

    public ConvertTemperature_Service() {
        super(__getWsdlLocation(), CONVERTTEMPERATURE_QNAME);
    }

    public ConvertTemperature_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONVERTTEMPERATURE_QNAME, features);
    }

    public ConvertTemperature_Service(URL wsdlLocation) {
        super(wsdlLocation, CONVERTTEMPERATURE_QNAME);
    }

    public ConvertTemperature_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONVERTTEMPERATURE_QNAME, features);
    }

    public ConvertTemperature_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConvertTemperature_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConvertTemperature
     */
    @WebEndpoint(name = "ConvertTemperaturePort")
    public ConvertTemperature getConvertTemperaturePort() {
        return super.getPort(new QName("http://webservice.plscience.pgcc.ufjf.br/", "ConvertTemperaturePort"), ConvertTemperature.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConvertTemperature
     */
    @WebEndpoint(name = "ConvertTemperaturePort")
    public ConvertTemperature getConvertTemperaturePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.plscience.pgcc.ufjf.br/", "ConvertTemperaturePort"), ConvertTemperature.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONVERTTEMPERATURE_EXCEPTION!= null) {
            throw CONVERTTEMPERATURE_EXCEPTION;
        }
        return CONVERTTEMPERATURE_WSDL_LOCATION;
    }

}
